server:
  #application:
    #name: authentication-service
  port: 2222 #443
  forward-headers-strategy: FRAMEWORK
# register service registry (discovery server)
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:1111/eureka
      #defaultZone: http://user:password@carrental-registry.northeurope.azurecontainer.io:1111/eureka
      defaultZone: https://carrental-registry.azurewebsites.net:443/eureka
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
  show-sql: true
  h2:
  console:
    enabled: true
jwt:
  header: Authorization
  secret: 3ef572f7769d78d
  expiration: 7200
allow:
  origin: localhost
